# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 2.7
python: 3.6

install:
  - pip install numpy
  - pip install scipy
  - pip install matplotlib
  - pip install lmfit
  - pip install PyQt5
  - pip install pandas

