sudo: false

dist: xenial
services:
  - xvfb

language: python


python:
    - 3.6
    - 3.7
    - 3.8

env: 
    - version=latest
    - verison=minimum


before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - python -m pip install --upgrade setuptools

addons:
  apt:
    packages:
    - libxkbcommon-x11-0


install:
  - python -m pip install --upgrade pip
  - if [[ $version == latest ]]; then python -m pip install --upgrade numpy scipy matplotlib pandas tqdm lmfit ; fi
  - if [[ $version == minimum ]]; then pip install numpy==1.16.6 ; fi
  - if [[ $version == minimum ]]; then pip install -r requirements.txt ; fi
  - pip install codecov
  - python setup.py install
  - pip list


script:
  - cd pysprint/tests
  - python -m unittest
  - coverage run -m unittest


after_success:
  - codecov