sudo: false

language: python


python:
    - 3.5
    - 3.6
    - 3.7


env:
    - version=minimum  
    - version=latest


before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"


install:

  - if [[ $version == minimum ]]; then pip install matplotlib==3.1.1 numpy==1.17.1 scipy==1.3.1 pandas==0.25.1 lmfit==0.9.13 PyQt5==5.13.0 ; fi
  - if [[ $version == latest ]]; then pip install -r requirements.txt ; fi
  - pip list


script:
  - cd Interferometry/tests
  - python test_MainApp.py