env:
  global:
    - TWINE_USERNAME=Ptrskay
    - DOCKER_IMAGE_LINUX_32=daald/ubuntu32:xenial
    - DOCKER_CONTAINER_LINUX_32=ubuntu32_container

stages:
  - Testing
  # Architectures supported:
  # - manylinux1_x86_64 py3.7, 3.8
  # - osx py3.7, 3.8
  - name: Deploying
    if: tag IS present

jobs:
  allow_failures:
    - os: osx
  include:
    - stage: Test
      name: "Python=3.7 linux x86_64"
      os: linux
      python: 3.7
      services:
        - xvfb
      install:
        - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
        - export PATH="$HOME/.cargo/bin:$PATH"
        - which python
        - which python3
        - which pip3
        - pyenv global 3.7.1
        - pip3 install --upgrade pip
        - pip3 install -r requirements.txt
        - pip3 install lmfit dask pytest coverage codecov
        - pip3 install setuptools setuptools_rust
        - python3 setup.py develop
      script:
        - cd pysprint/tests
        - coverage run --source=pysprint -m pytest
        - coverage report -m
        - cd ..
        - cd ..

    - name: "Python=3.7 OSX"
      os: osx
      python: 3.7
      language: generic
      services:
        - xvfb
      env:
        - PIP=pip3
        - PYTHON=python3
      install:
        - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly -y
        - export PATH="$HOME/.cargo/bin:$PATH"
        - $PIP install -r requirements.txt
        - $PIP install lmfit dask numba pytest coverage codecov
        - $PIP install setuptools setuptools_rust
        - $PYTHON setup.py develop
      script:
        - cd pysprint/tests
        - pytest -vv
        - cd ..
        - cd ..

    - stage: Deploying
    - name: "manylinux_x86_64"
      # Job generating the wheels for Linux 64-bit platforms
      os: linux
      sudo: required
      env:
        - CIBW_SKIP="*manylinux_i686* cp27-* cp34-* pp27-*"
        - PIP=pip3
        - PYTHON=python3
      services:
        - docker
      script: .ci/deploy.sh
    - name: "manylinux_i686"
      # Job generating the wheels for Linux 32-bit platforms
      os: linux
      sudo: required
      env:
        - CIBW_SKIP="*manylinux_x86_64* cp34-* cp27-*"
        - PIP=pip3
        - PYTHON=python3
      services:
        - docker
      script: .ci/deployi686.sh
    - name: "OSX"
      os: osx
      sudo: required
      language: generic
      env:
        - CIBW_SKIP="cp27-* cp34-*"
        - PIP=pip3
        - PYTHON=python3
      script: .ci/deploy.sh
