sudo: false

language: python


python:
    - 3.5
    - 3.6
    - 3.7


env:
    - version=minimum  
    - version=latest


before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"


install:
  - pip install -r requirements.txt

script:
  - cd Interferometry/tests
  - python test_MainApp.py