# Disable sudo to speed up the build
sudo: false


# Set the build language to Python
language: python

# Set the python version to 2.7
python: 3.6

before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"


install:
  - pip install -r requirements.txt

script:
  - cd tests
  - python test_MainApp.py