sudo: false


dist: xenial

services:
  - xvfb

language: python

python:
    - 3.6
    - 3.7
    - 3.8

env: 
    - version=latest
    - verison=minimum
    - version=withextras

before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
  - python -m pip install --upgrade setuptools

addons:
  apt:
    packages:
    - libxkbcommon-x11-0


install:
  - python -m pip install --upgrade pip
  - if [[ $version == withextras ]]; then python -m pip install --upgrade numpy scipy matplotlib pandas lmfit numba ; fi
  - if [[ $version == latest ]]; then python -m pip install --upgrade numpy scipy matplotlib pandas ; fi
  - if [[ $version == minimum ]]; then pip install -r requirements.txt --force-reinstall ; fi
  # this should be called explicitly to actually get the right numpy version
  - if [[ $version == minimum ]]; then pip install numpy==1.16.0 ; fi
  - pip install codecov coverage flake8 
  - python setup.py install
  - pip list

before_script:
  # stop upon syntax errors or undefined names
  - flake8 pysprint/ --count --select=E9,F63,F72,F82 --show-source --statistics

script:
  - cd pysprint/tests
  - coverage run --source=pysprint -m pytest
  - coverage report -m

after_success:
  - codecov