name: pysprint-dev
channels:
  - conda-forge
  - anaconda
dependencies:
  # required and optional
  - python=3.8
  - numpy>=1.15,<1.19.0
  - matplotlib
  - pandas
  - scipy
  - numba>=0.46.0
  - lmfit
  - Jinja2
  - dask
  - setuptools-rust
  - wheel

  # docs
  - sphinx
  - nbsphinx
  - recommonmark
  - sphinx_rtd_theme
  - nbconvert

  # Strictly speaking this is not neseccary, but better safe than sorry
  - cython>=0.29.16
  - ipython>=7.11.1
  - jupyter
  - ipykernel
  - ipywidgets
  - nbformat
  - notebook>=5.7.5
  - pip

  # code checks
  - black
  - flake8
  - pytest>=5.0.1
  - codecov
  - coverage
  - tox
