package:
  name: pysprint
  version: "0.0.24"

source:
  fn: pysprint-0.0.24.tar.gz
  url: https://pypi.io/packages/source/p/pysprint/pysprint-0.0.24.tar.gz
  md5: b63f80c9e1a28d576a66ae701df9ced9

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - matplotlib

  run:
    - python
    - numpy
    - scipy
    - matplotlib

test:
  imports:
    - pysprint


about:
  home: https://github.com/Ptrskay3/PySprint
  license: MIT
  summary: 'Spectrally refined interferometry for Python'
