{% set name = "pysprint" %}
{% set version = "0.12.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

requirements:
  host:
    - matplotlib
    - numpy >=1.16.6
    - pandas
    - pip
    - python
    - scipy
  run:
    - matplotlib
    - numpy >=1.16.6
    - pandas
    - python
    - scipy

test:
  imports:
    - pysprint
    - pysprint.api
    - pysprint.core
    - pysprint.core.bases
    - pysprint.core.methods
    - pysprint.mpl_tools
    - pysprint.tests
    - pysprint.utils

about:
  home: "https://github.com/Ptrskay3/PySprint"
  license: MIT

